# Generated by Django 5.2.7 on 2026-07-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_maintain', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='buddy_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='delivery_method',
            field=models.CharField(default='Pick Up', max_length=50),
        ),
        migrations.AddField(
            model_name='branch',
            name='pickup_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='pickup_hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
