# Generated by Django 5.2.7 on 2026-07-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_maintain', '0004_booking_buddy_group_booking_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='buying_price',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='buying_price',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='selling_price',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
