# Generated by Django 5.2.7 on 2026-07-28 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_maintain', '0007_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockout',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='stock_maintain.branch'),
        ),
    ]
