# Generated by Django 5.2.7 on 2026-07-28 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_maintain', '0009_alter_product_unique_together_alter_product_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='branch',
        ),
    ]
